name: food_ninja
description: A new Flutter project.
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.7.1
  dio: ^5.1.2
  equatable: ^2.0.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^4.0.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.6
  geolocator: ^9.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  latlong2: ^0.8.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"

  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
# flutter pub get
# flutter pub run flutter_launcher_icons
