// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDtf654ha_rJ6_Ia4NFRPZCLl0pCfKa3o',
    appId: '1:665208381476:web:2c0df0e7741a2bf58af8b1',
    messagingSenderId: '665208381476',
    projectId: 'food-ninja-f7b7c',
    authDomain: 'food-ninja-f7b7c.firebaseapp.com',
    storageBucket: 'food-ninja-f7b7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7H07umbLHgyQ3HwypY-CqauI_4b4eywo',
    appId: '1:665208381476:android:e842564e4422cb3d8af8b1',
    messagingSenderId: '665208381476',
    projectId: 'food-ninja-f7b7c',
    storageBucket: 'food-ninja-f7b7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBViYz3hVxzQZW_PbG5dsvuvAHMHjpRywY',
    appId: '1:665208381476:ios:1ca700afeb1555178af8b1',
    messagingSenderId: '665208381476',
    projectId: 'food-ninja-f7b7c',
    storageBucket: 'food-ninja-f7b7c.appspot.com',
    iosClientId: '665208381476-eg3dt1phf02bk05bus035nmtg7qofbni.apps.googleusercontent.com',
    iosBundleId: 'com.shokhrukhbek.foodNinja',
  );
}
